# Generated by Django 5.2.1 on 2025-05-17 03:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0002_alter_alertmitretechnique_alert'),
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MitreTactic',
            fields=[
                ('tactic_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MitreTechnique',
            fields=[
                ('technique_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('is_subtechnique', models.BooleanField(default=False)),
                ('version', models.CharField(max_length=20)),
                ('parent_technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtechniques', to='mitre.mitretechnique')),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueTactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitre.mitretactic')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitre.mitretechnique')),
            ],
            options={
                'unique_together': {('technique', 'tactic')},
            },
        ),
        migrations.AddField(
            model_name='mitretechnique',
            name='tactics',
            field=models.ManyToManyField(related_name='techniques', through='mitre.TechniqueTactic', to='mitre.mitretactic'),
        ),
        migrations.CreateModel(
            name='CaseMitreTechnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitre_module_techniques', to='cases.case')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitre.mitretechnique')),
            ],
            options={
                'unique_together': {('case', 'technique')},
            },
        ),
        migrations.CreateModel(
            name='AlertMitreTechnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitre_module_techniques', to='alerts.alert')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitre.mitretechnique')),
            ],
            options={
                'unique_together': {('alert', 'technique')},
            },
        ),
    ]
