# Generated by Django 5.2.1 on 2025-05-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitre', '0002_casemitretechnique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniquetactic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
