version: '3.9'

services:
  web:
    build: 
      context: .
      args:
        - UV_LINK_MODE=copy
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./api:/app/api
      - ./core:/app/core
      - ./static:/app/static
      - static_volume:/app/staticfiles  # Mount static files volume
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - UV_LINK_MODE=copy
    depends_on:
      - db
  
  # Nginx service to serve static files
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static  # Mount static files volume
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Custom nginx configuration
    depends_on:
      - web

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:  # Define a volume for static files
  uv_cache:  # Volume for uv cache 