# Generated by Django 5.2.1 on 2025-05-17 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0001_initial'),
        ('mitre', '0001_initial'),
        ('observables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casemitretechnique',
            name='technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique_cases', to='mitre.mitretechnique'),
        ),
        migrations.AddField(
            model_name='caseobservable',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_observables', to='cases.case'),
        ),
        migrations.AddField(
            model_name='caseobservable',
            name='observable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_observables', to='observables.observable'),
        ),
        migrations.AddField(
            model_name='case',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.caseseverity'),
        ),
        migrations.AddField(
            model_name='casestatus',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_statuses', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casestatus'),
        ),
        migrations.AddField(
            model_name='casetemplate',
            name='default_severity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.caseseverity'),
        ),
        migrations.AddField(
            model_name='casetemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_templates', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='case',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.casetemplate'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cases.case'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='cases.taskstatus'),
        ),
        migrations.AlterUniqueTogether(
            name='casecustomfielddefinition',
            unique_together={('organization', 'technical_name')},
        ),
        migrations.AlterUniqueTogether(
            name='casecustomfieldvalue',
            unique_together={('case', 'field_definition')},
        ),
        migrations.AlterUniqueTogether(
            name='casemitretechnique',
            unique_together={('case', 'technique')},
        ),
        migrations.AlterUniqueTogether(
            name='caseobservable',
            unique_together={('case', 'observable')},
        ),
        migrations.AlterUniqueTogether(
            name='casestatus',
            unique_together={('name', 'organization')},
        ),
    ]
