# Generated by Django 5.2.1 on 2025-05-17 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('alerts', '0004_alter_alert_options_alter_alertcomment_options_and_more'),
        ('cases', '0002_initial'),
        ('mitre', '0003_alter_techniquetactic_id'),
        ('observables', '0002_alter_observabletype_options_alter_paplevel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='casecomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='caseseverity',
            options={'ordering': ['level_order'], 'verbose_name_plural': 'Case Severities'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['case', 'order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['organization'], name='cases_case_organiz_169787_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['organization', 'status'], name='cases_case_organiz_6de08e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['organization', 'severity'], name='cases_case_organiz_7e3b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['organization', 'assignee'], name='cases_case_organiz_ebdff6_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['reporter'], name='cases_case_reporte_0ba128_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['organization', 'created_at'], name='cases_case_organiz_d6c930_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['organization', 'updated_at'], name='cases_case_organiz_5fa431_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['organization', 'closed_at'], name='cases_case_organiz_8ea2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'updated_at'], name='cases_case_status__27ccdf_idx'),
        ),
        migrations.AddIndex(
            model_name='casecomment',
            index=models.Index(fields=['case', 'created_at'], name='cases_casec_case_id_21ee37_idx'),
        ),
        migrations.AddIndex(
            model_name='casecomment',
            index=models.Index(fields=['user', 'created_at'], name='cases_casec_user_id_05072a_idx'),
        ),
        migrations.AddIndex(
            model_name='casecustomfielddefinition',
            index=models.Index(fields=['organization', 'field_type'], name='cases_casec_organiz_ea9a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='casecustomfielddefinition',
            index=models.Index(fields=['organization', 'is_filterable'], name='cases_casec_organiz_e908c7_idx'),
        ),
        migrations.AddIndex(
            model_name='casecustomfieldvalue',
            index=models.Index(fields=['case', 'field_definition'], name='cases_casec_case_id_e782aa_idx'),
        ),
        migrations.AddIndex(
            model_name='casecustomfieldvalue',
            index=models.Index(fields=['field_definition', 'value_text'], name='cases_casec_field_d_3220c4_idx'),
        ),
        migrations.AddIndex(
            model_name='casecustomfieldvalue',
            index=models.Index(fields=['field_definition', 'value_number'], name='cases_casec_field_d_db8882_idx'),
        ),
        migrations.AddIndex(
            model_name='casecustomfieldvalue',
            index=models.Index(fields=['field_definition', 'value_boolean'], name='cases_casec_field_d_4cc6e7_idx'),
        ),
        migrations.AddIndex(
            model_name='casecustomfieldvalue',
            index=models.Index(fields=['field_definition', 'value_date'], name='cases_casec_field_d_7b88d3_idx'),
        ),
        migrations.AddIndex(
            model_name='casemitretechnique',
            index=models.Index(fields=['case'], name='cases_casem_case_id_e3e8f3_idx'),
        ),
        migrations.AddIndex(
            model_name='casemitretechnique',
            index=models.Index(fields=['technique'], name='cases_casem_techniq_b66274_idx'),
        ),
        migrations.AddIndex(
            model_name='casemitretechnique',
            index=models.Index(fields=['linked_by'], name='cases_casem_linked__1237e9_idx'),
        ),
        migrations.AddIndex(
            model_name='casemitretechnique',
            index=models.Index(fields=['linked_at'], name='cases_casem_linked__3184f2_idx'),
        ),
        migrations.AddIndex(
            model_name='caseobservable',
            index=models.Index(fields=['case', 'sighted_at'], name='cases_caseo_case_id_9178ca_idx'),
        ),
        migrations.AddIndex(
            model_name='caseobservable',
            index=models.Index(fields=['observable', 'sighted_at'], name='cases_caseo_observa_52bf8b_idx'),
        ),
        migrations.AddIndex(
            model_name='casestatus',
            index=models.Index(fields=['organization', 'is_default_open_status'], name='cases_cases_organiz_741d45_idx'),
        ),
        migrations.AddIndex(
            model_name='casestatus',
            index=models.Index(fields=['organization', 'is_terminal_status'], name='cases_cases_organiz_ea0a50_idx'),
        ),
        migrations.AddIndex(
            model_name='casetemplate',
            index=models.Index(fields=['organization'], name='cases_caset_organiz_91ee33_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['case', 'status'], name='cases_task_case_id_61ba21_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['case', 'assignee'], name='cases_task_case_id_3ce8ea_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['case', 'due_date'], name='cases_task_case_id_be6fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'due_date'], name='cases_task_assigne_b13642_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'due_date'], name='cases_task_status__4d17bf_idx'),
        ),
    ]
