# Generated by Django 5.2.1 on 2025-05-16 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_metric_notificationevent_dashboard_dashboardwidget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MISPInstance',
            fields=[
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('default_distribution', models.IntegerField(choices=[(0, 'Your Organization Only'), (1, 'This Community Only'), (2, 'Connected Communities'), (3, 'All Communities')], default=0)),
                ('default_threat_level', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low'), (4, 'Undefined')], default=2)),
                ('default_analysis', models.IntegerField(choices=[(0, 'Initial'), (1, 'Ongoing'), (2, 'Completed')], default=0)),
                ('import_filter_tags', models.JSONField(blank=True, null=True)),
                ('export_default_tags', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_import_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
            options={
                'verbose_name': 'MISP Instance',
                'verbose_name_plural': 'MISP Instances',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MISPImport',
            fields=[
                ('import_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('import_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PARTIAL', 'Partial')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('imported_events_count', models.IntegerField(default=0)),
                ('imported_attributes_count', models.IntegerField(default=0)),
                ('created_alerts_count', models.IntegerField(default=0)),
                ('created_observables_count', models.IntegerField(default=0)),
                ('updated_observables_count', models.IntegerField(default=0)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('misp_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mispinstance')),
            ],
        ),
        migrations.CreateModel(
            name='MISPExport',
            fields=[
                ('export_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('misp_event_uuid', models.UUIDField()),
                ('export_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PARTIAL', 'Partial')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('exported_observables_count', models.IntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.case')),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('misp_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mispinstance')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('output_format', models.CharField(choices=[('MARKDOWN', 'Markdown'), ('DOCX', 'Microsoft Word'), ('PDF', 'PDF')], max_length=10)),
                ('template_content', models.TextField()),
                ('default_sections', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_format', models.CharField(max_length=10)),
                ('file_path', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('included_sections', models.JSONField(default=list)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.case')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.reporttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ObservableMISPMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misp_event_uuid', models.UUIDField()),
                ('misp_attribute_uuid', models.UUIDField()),
                ('last_sync_timestamp', models.DateTimeField(auto_now=True)),
                ('misp_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mispinstance')),
                ('observable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.observable')),
            ],
            options={
                'unique_together': {('observable', 'misp_instance', 'misp_attribute_uuid')},
            },
        ),
    ]
