# Generated by Django 5.2.1 on 2025-05-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mispinstance_mispimport_mispexport_reporttemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('STATUS_CHANGE', 'Status Change'), ('ASSIGN', 'Assign'), ('PUBLISH', 'Publish'), ('TEST_CONNECTION', 'Test Connection'), ('IMPORT', 'Import'), ('MISP_EXPORT', 'MISP Export'), ('GENERATE_REPORT', 'Generate Report')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('ALERT', 'Alert'), ('CASE', 'Case'), ('TASK', 'Task'), ('OBSERVABLE', 'Observable'), ('CASE_OBSERVABLE', 'Case Observable'), ('ALERT_OBSERVABLE', 'Alert Observable'), ('CASE_COMMENT', 'Case Comment'), ('ALERT_COMMENT', 'Alert Comment'), ('CASE_MITRE_TECHNIQUE', 'Case MITRE Technique'), ('MISP_INSTANCE', 'MISP Instance'), ('REPORT_TEMPLATE', 'Report Template'), ('KB_ARTICLE', 'Knowledge Base Article'), ('TIMELINE_EVENT', 'Timeline Event')], max_length=30),
        ),
    ] 