# Generated by Django 5.2.1 on 2025-05-17 00:15

from django.db import migrations

def add_audit_permissions(apps, schema_editor):
    Permission = apps.get_model('api', 'Permission')
    
    # Create permission for viewing audit logs
    Permission.objects.get_or_create(
        code='view_audit_logs',
        defaults={
            'name': 'View Audit Logs',
            'description': 'Permission to view system audit logs'
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_auditlog_action_type_alter_auditlog_entity_type'),
    ]

    operations = [
        migrations.RunPython(add_audit_permissions),
    ] 