# Generated by Django 5.2.1 on 2025-05-17 03:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='cases.case')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='accounts.organization')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['case'], name='timeline_ti_case_id_9a0d77_idx'), models.Index(fields=['organization'], name='timeline_ti_organiz_494a27_idx'), models.Index(fields=['event_type'], name='timeline_ti_event_t_0e25e4_idx'), models.Index(fields=['occurred_at'], name='timeline_ti_occurre_35ddb0_idx')],
            },
        ),
    ]
