# Generated by Django 5.2.1 on 2025-05-17 06:17

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0003_alter_case_options_alter_casecomment_options_and_more'),
        ('timeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='timelineevent',
            name='timeline_ti_case_id_9a0d77_idx',
        ),
        migrations.RemoveIndex(
            model_name='timelineevent',
            name='timeline_ti_organiz_494a27_idx',
        ),
        migrations.RemoveIndex(
            model_name='timelineevent',
            name='timeline_ti_event_t_0e25e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='timelineevent',
            name='timeline_ti_occurre_35ddb0_idx',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Flag para marcar eventos críticos ou importantes'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='occurred_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['case', 'occurred_at'], name='timeline_ti_case_id_103ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['organization', 'occurred_at'], name='timeline_ti_organiz_f2b72b_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='timeline_ti_event_t_c1be22_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['target_entity_type', 'target_entity_id'], name='timeline_ti_target__697ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['is_important', 'occurred_at'], name='timeline_ti_is_impo_4da70f_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['actor', 'occurred_at'], name='timeline_ti_actor_i_21efec_idx'),
        ),
    ]
