# Generated by Django 5.2.1 on 2025-05-17 03:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(choices=[('COUNT', 'Count'), ('AVERAGE', 'Average'), ('SUM', 'Sum'), ('PERCENTAGE', 'Percentage'), ('CUSTOM', 'Custom')], max_length=20)),
                ('entity_type', models.CharField(max_length=50)),
                ('calculation_query', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('dashboard_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('widget_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('LINE_CHART', 'Line Chart'), ('BAR_CHART', 'Bar Chart'), ('PIE_CHART', 'Pie Chart'), ('TABLE', 'Table'), ('KPI_CARD', 'KPI Card'), ('COUNTER', 'Counter'), ('GAUGE', 'Gauge')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('position', models.JSONField(default=dict)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='metrics.dashboard')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='metrics.metric')),
            ],
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('granularity', models.CharField(max_length=10)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='metrics.metric')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='accounts.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['organization'], name='metrics_das_organiz_d4935e_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['is_system'], name='metrics_das_is_syst_5baa3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='metricsnapshot',
            index=models.Index(fields=['metric', 'organization', 'date'], name='metrics_met_metric__eb8cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='metricsnapshot',
            index=models.Index(fields=['date'], name='metrics_met_date_2fdb9c_idx'),
        ),
        migrations.AddIndex(
            model_name='metricsnapshot',
            index=models.Index(fields=['organization'], name='metrics_met_organiz_c119dd_idx'),
        ),
    ]
