# Generated by Django 5.2.1 on 2025-05-17 06:17

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observabletype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='paplevel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tlplevel',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='observable',
            unique_together={('type', 'value')},
        ),
        migrations.AddField(
            model_name='observable',
            name='first_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='observable',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observable',
            name='reputation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paplevel',
            name='color_code',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='tlplevel',
            name='color_code',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='observable',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tlplevel',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='observable',
            index=models.Index(fields=['value'], name='observables_value_c528ee_idx'),
        ),
        migrations.AddIndex(
            model_name='observable',
            index=models.Index(fields=['type', 'value'], name='observables_type_id_d37dac_idx'),
        ),
        migrations.AddIndex(
            model_name='observable',
            index=models.Index(fields=['is_ioc'], name='observables_is_ioc_c3bb9d_idx'),
        ),
        migrations.AddIndex(
            model_name='observable',
            index=models.Index(fields=['tlp_level'], name='observables_tlp_lev_40d3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='observable',
            index=models.Index(fields=['pap_level'], name='observables_pap_lev_ca01e9_idx'),
        ),
        migrations.AddIndex(
            model_name='observable',
            index=models.Index(fields=['first_seen_at'], name='observables_first_s_0334b5_idx'),
        ),
        migrations.AddIndex(
            model_name='observable',
            index=models.Index(fields=['last_seen_at'], name='observables_last_se_4e807c_idx'),
        ),
        migrations.AddIndex(
            model_name='observable',
            index=models.Index(fields=['reputation_score'], name='observables_reputat_97c126_idx'),
        ),
        migrations.AddIndex(
            model_name='observable',
            index=models.Index(fields=['added_by'], name='observables_added_b_b1899d_idx'),
        ),
    ]
