# Generated by Django 5.2.1 on 2025-05-17 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alertmitretechnique_alert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertMitreTechnique',
        ),
    ]
