# Generated by Django 5.2.1 on 2025-05-17 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('alerts', '0003_delete_alertmitretechnique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='alertcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='alertseverity',
            options={'ordering': ['level_order'], 'verbose_name_plural': 'Alert Severities'},
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', 'is_deleted'], name='alerts_aler_organiz_cf1914_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', 'status'], name='alerts_aler_organiz_ca0a05_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', 'severity'], name='alerts_aler_organiz_b486bc_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', 'assignee'], name='alerts_aler_organiz_cad791_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', 'created_at'], name='alerts_aler_organiz_d3d37e_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', 'first_seen_at'], name='alerts_aler_organiz_44984d_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', 'is_deleted', 'created_at'], name='alerts_aler_organiz_a47b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['source_system', 'external_alert_id'], name='alerts_aler_source__e3bfed_idx'),
        ),
        migrations.AddIndex(
            model_name='alertcomment',
            index=models.Index(fields=['alert', 'created_at'], name='alerts_aler_alert_i_a791e1_idx'),
        ),
        migrations.AddIndex(
            model_name='alertcomment',
            index=models.Index(fields=['user', 'created_at'], name='alerts_aler_user_id_8f6a83_idx'),
        ),
        migrations.AddIndex(
            model_name='alertcustomfielddefinition',
            index=models.Index(fields=['organization', 'field_type'], name='alerts_aler_organiz_1fd085_idx'),
        ),
        migrations.AddIndex(
            model_name='alertcustomfielddefinition',
            index=models.Index(fields=['organization', 'is_filterable'], name='alerts_aler_organiz_3e64f9_idx'),
        ),
        migrations.AddIndex(
            model_name='alertcustomfieldvalue',
            index=models.Index(fields=['alert', 'field_definition'], name='alerts_aler_alert_i_1ab40b_idx'),
        ),
        migrations.AddIndex(
            model_name='alertcustomfieldvalue',
            index=models.Index(fields=['field_definition', 'value_text'], name='alerts_aler_field_d_c3bb51_idx'),
        ),
        migrations.AddIndex(
            model_name='alertcustomfieldvalue',
            index=models.Index(fields=['field_definition', 'value_number'], name='alerts_aler_field_d_bc8e20_idx'),
        ),
        migrations.AddIndex(
            model_name='alertcustomfieldvalue',
            index=models.Index(fields=['field_definition', 'value_boolean'], name='alerts_aler_field_d_d8b7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='alertcustomfieldvalue',
            index=models.Index(fields=['field_definition', 'value_date'], name='alerts_aler_field_d_35b6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='alertobservable',
            index=models.Index(fields=['alert', 'sighted_at'], name='alerts_aler_alert_i_dff2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='alertobservable',
            index=models.Index(fields=['observable'], name='alerts_aler_observa_851fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='alertstatus',
            index=models.Index(fields=['organization', 'is_default_open_status'], name='alerts_aler_organiz_20a32c_idx'),
        ),
        migrations.AddIndex(
            model_name='alertstatus',
            index=models.Index(fields=['organization', 'is_terminal_status'], name='alerts_aler_organiz_bb3430_idx'),
        ),
    ]
